#! /bin/bash
# Activate auto completion for environmental variable
shopt -s direxpand

# Setting all neccessary paths
# General settings
export WORKSPACE=$HOME
export DATA=/data
export SOFTWARE=$WORKSPACE/Software
export PY_SCRIPTS=$WORKSPACE/Python
export MODELS=$WORKSPACE/Models

export PYTHONPATH=$PYTHONPATH:$PY_SCRIPTS
export PATH=$PATH:$SOFTWARE/grib_api-1.28.0/bin/bin

# ICON docker
set_up () {
    opt1=${1}
    opt2=${2}
    opt_str="Valid options: icon aes, icon les"
    case $opt1 in
        icon)
            export ICON_POOL=$DATA/icon/pool
            case $opt2 in
                aes)
                    echo "Setting ICON-AES"
                    export ICON_ROOT=$MODELS/icon/icon-aes
                    ;;
                les)
                    echo "Setting ICON-LES"
                    export ICON_ROOT=$MODELS/icon/icon-les
                    ;;
                *)
                    echo ${opt_str}
                    ;;
            esac
            update_icon() {
                cd $ICON_ROOT
                git fetch
                git submodule update --recursive
                git pull --recurse-submodules
                cd externals/jsbach
                git switch dev
                git pull
                git merge dev
            }
            ;;
        blue)
            export BLUE_ROOT=$MODELS/blue
            export BLUE_MODEL=${BLUE_ROOT}/blue_code
            export BLUE_SCRIPTS=${BLUE_ROOT}/blue_RunScripts
            # Activate conda environ
            use_conda
            conda activate blue_env
            ;;
        *)
        echo ${opt_str}
        ;;
    esac
}

# Include Panoply
alias panoply=${SOFTWARE}/PanoplyJ/panoply.sh

# Name
LRZNAME=ra46zot
DKRZNAME=m300917

# Mounting of network resources
src_data() {
    target=${1}
    mode=${2}
    case $target in
        saga)
            echo "Mounting saga/work"
            sshfs sfalk@saga.sigma2.no:/cluster/work/users/sfalk ${DATA}/saga
            ;;
        input_data)
            echo "Mounting saga/input_data"
            sshfs sfalk@saga.sigma2.no:/cluster/projects/nn9188k/OsloCTM3 ${DATA}/CTM3_input_data
            ;;
        BrXplo)
            echo "Mounting BrXplo on pfs"
            sshfs hy0485@uc1.scc.kit.edu:/pfs/imk/imk-asf/common/results/EMAC/BrXplo ${DATA}/BrXplo_data
            ;;
        CTM3_Oivind)
            echo "Mounting /div/pdo/cixpag/oivinho/CTM3_output/"
            sshfs sfalk@pdo.uio.no:/div/pdo/cixpag/oivinho/CTM3_output/ ${DATA}/CTM3_Oivind_data
            ;;
        astra)
            echo "Mounting ASTRA"
            sshfs sfalk@login.uio.no:/net/astra/astra-01/sfalk/ ${DATA}/astra
            ;;
        nird)
            echo "Mounting /tos-project1/NS2806K/sfalk/"
            sshfs sfalk@login.nird.sigma2.no:/tos-project1/NS2806K/sfalk/ ${DATA}/nird
            ;;
        uio_home)
            echo "Mounting /uio/kant/geo-metos-u4/sfalk/"
            sshfs sfalk@login.uio.no:/uio/kant/geo-metos-u1/sfalk/privat/Documents/ /kant
            ;;
        nas)
            echo "Mounting nas"
            sudo mount -t davfs -o uid=sfalk,gid=sfalk https://webdisk.ads.mwn.de/hcwebdav $DATA/nas
            ;;
        *)
            echo "No valid mount point!"
            echo "Options: saga; astra; nird; uio_home; nas"
    esac
    #
}

unsrc_data() {
    tgt=${1}
    fusermount -uz $tgt

}

use_conda() {
    # >>> conda initialize >>>
    # !! Contents within this block are managed by 'conda init' !!
    __conda_setup="$('/home/sfalk/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "/home/sfalk/anaconda3/etc/profile.d/conda.sh" ]; then
            . "/home/sfalk/anaconda3/etc/profile.d/conda.sh"
        else
            export PATH="/home/sfalk/anaconda3/bin:$PATH"
        fi
    fi
    unset __conda_setup
    # <<< conda initialize <<<
}

# Alias
alias ssh_centos='ssh -X -i ~/.ssh/iaas-cloud_ceres.key.pub centos@158.39.75.138'

echo "Setting work environment..."
